buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.setup]
nixPkgs = ["nodejs_20", "bun"]
# Bun 1.3.4
# track latest commit sha: https://github.com/NixOS/nixpkgs/blob/nixpkgs-unstable/pkgs/by-name/bu/bun/package.nix
nixpkgsArchive = 'd667853dbfa2808057c4cf25079ac560d7b60914'

[phases.install]
dependsOn = ["setup"]
cacheDirectories = [
  "node_modules",
  "node_modules/.cache",
  "/root/.bun/install/cache"]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
dependsOn = ["install"]
cmds = ["bun run build"]
cacheDirectories = [
  "node_modules",
  "node_modules/.cache",
  ".svelte-kit"]

[start]
cmd = "bun serve.js"

# Ensure build directory is included in the final image
[staticAssets]
"build" = "build"
